hydra:
  run:
    dir: ${logs_path}/hydra/singlerun/${now:%Y-%m-%d}/${now:%H-%M-%S}/${area.name}
  sweep:
    dir: ${logs_path}/hydra/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${area.name}
  job_logging:
    formatters:
      detailed:
        format: '[%(levelname)s|%(module)s|L%(lineno)d] %(asctime)s: %(message)s'
        datefmt: '%Y-%m-%dT%H:%M:%S%z'
    handlers:
      file:
        class: logging.FileHandler
        level: INFO
        formatter: detailed
        filename: ${hydra.runtime.output_dir}/${hydra:job.name}.log
      console:
        class: logging.StreamHandler
        level: INFO
        formatter: detailed
    root:
      level: INFO
      handlers: [file, console]
